### ISSUE TITLE
UI Module should include Pane items as well as Panel items

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/UIModules#10] opened 2016-11-04 22:18 UTC
UI Module doesn’t detect items higher levels than the panel. Example is tab controls or sub panels.

Looks like it would be capable just by adding a property node or two.
 
this snippet is in a few existing VI’s, this is oversimplified in some cases… but indicates what I am looking for
![1](https://cloud.githubusercontent.com/assets/20828732/20024111/0b1dac0a-a2aa-11e6-9fdf-57157ce1490c.png)

This is how I think it should be to include elements inside of “panes” which I believe is how Labview refers to tab controls as. 
![2](https://cloud.githubusercontent.com/assets/20828732/20024113/144ad672-a2aa-11e6-965a-2467c3f153ec.png)

It could probably be modified to include both Panel-->controls and Panel-->Panes-->Controls just by concatenating the result arrays.

**Comment by smithed** [comment] 2016-11-05 01:33
I doubt it can run in an exe, but if it can I think this would do the job:
http://zone.ni.com/reference/en-XX/help/371361N-01/glang/tref_traverse_for_references/

**Comment by pollockm** [comment] 2016-11-06 02:22
Rejected as duplicate of #8, which was already fixed last week.

**Closed by pollockm** 2016-11-06 02:22 UTC
